const items = [
  {
    id: 1,
    name: 'rose',
    description: 'very good for your girlfriend',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
    category: 'rose',
  },
  {
    id: 2,
    name: 'primrose bouquet',
    description: 'awesome for your mother',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
    category: 'bouquet',
  },
  {
    id: 3,
    name: 'veryred pot',
    description: 'perfect for your living room',
    stock: 100,
    price: 50,
    photo: '../../assets/rose.jpg',
    category: 'pot',
  },
  {
    id: 4,
    name: 'Chair Arrangement',
    description: 'make the wedding aisle oh-so-beautiful',
    stock: 100,
    price: 120,
    photo: '../../assets/rose.jpg',
    category: 'wedding',
  },
  {
    id: 5,
    name: 'primrose',
    description: 'awesome for your mother',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
    category: 'rose',
  },
  {
    id: 6,
    name: 'colorful pot',
    description: 'good for your garden',
    stock: 100,
    price: 50,
    photo: '../../assets/rose.jpg',
    category: 'pot',
  },
  {
    id: 7,
    name: 'Altar Arrangement',
    description: 'will backdrop your ceremony photos',
    stock: 100,
    price: 120,
    photo: '../../assets/rose.jpg',
    category: 'wedding',
  },
];
export default items;
