const items = [
  {
    id: 1,
    name: 'rose',
    description: 'very good for your girlfriend',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
  },
  {
    id: 2,
    name: 'primrose',
    description: 'awesome for your mother',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
  },
  {
    id: 3,
    name: 'veryred',
    description: 'perfect for your father',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
  },
  {
    id: 4,
    name: 'rose',
    description: 'very good for your girlfriend',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
  },
  {
    id: 5,
    name: 'primrose',
    description: 'awesome for your mother',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
  },
  {
    id: 6,
    name: 'veryred',
    description: 'perfect for your father',
    stock: 100,
    price: 12,
    photo: '../../assets/rose.jpg',
  },
];
export default items;
